### ISSUE TITLE
einsum operation - kronecker multiply imp.

### ISSUE THREAD

**Issue by MultiTrickFox** [williamFalcon/pytorch-complex-tensor#9]

**Comment by developersfox** [comment]
The example
C = ComplexTensor([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
C[-1] , C[0, 0:-2, ...] or any indexing fails with 

complex_tensor.py", line 339, in size
size[-2] = size[-2] // 2
IndexError: list index out of range

I think the indexing was broken by a change a pytorch. I'm going to look into it, but please could you help me with this?
